# Generated by Django 5.0.4 on 2024-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_service_images_alter_service_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='base.image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='base.video'),
        ),
    ]
