# Generated by Django 5.0.4 on 2024-05-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
        migrations.RemoveField(
            model_name='service',
            name='videos',
        ),
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='base.image'),
        ),
        migrations.AddField(
            model_name='service',
            name='videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='base.video'),
        ),
    ]
