# Generated by Django 5.0.4 on 2024-05-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_service_images_remove_service_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='images',
        ),
        migrations.RemoveField(
            model_name='service',
            name='videos',
        ),
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(null=True, related_name='images', to='base.image'),
        ),
        migrations.AddField(
            model_name='service',
            name='videos',
            field=models.ManyToManyField(null=True, related_name='videos', to='base.video'),
        ),
    ]
