# Generated by Django 5.0.4 on 2024-05-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_service_images_alter_service_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='videos',
        ),
        migrations.AddField(
            model_name='service',
            name='videos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='base.video'),
        ),
    ]
