# Generated by Django 5.0.4 on 2024-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_service_videos_service_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
        migrations.AddField(
            model_name='service',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='minute',
            field=models.IntegerField(default=0),
        ),
    ]
