# Generated by Django 5.0.4 on 2024-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Произведение', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ImageField(default='', upload_to='./static/filesForService/gallery/'),
        ),
    ]
