# Generated by Django 5.0.4 on 2024-05-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_gallery_title_alter_gallery_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='image',
        ),
    ]
