# Generated by Django 5.0.4 on 2024-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_images_gallery_image'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS base_order_services;"),
        migrations.RunSQL("DROP TABLE IF EXISTS base_order;")
    ]
