# Generated by Django 5.0.6 on 2024-05-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='base.image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='videos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='base.video'),
        ),
    ]
