# Generated by Django 5.0.6 on 2024-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_service_images_alter_service_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('Text', models.TextField(null=True, verbose_name='Текст сообщения')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created'],
            },
        ),
    ]
