# Generated by Django 5.0.6 on 2024-05-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_messagefordirector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagefordirector',
            old_name='Text',
            new_name='text',
        ),
    ]
