# Generated by Django 4.2.13 on 2024-06-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_messagefordirector_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Состояние записи',
                'verbose_name_plural': 'Состояния записи',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана в'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена в'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed', to='base.conditionoforder', verbose_name='Запись подтверждена'),
        ),
    ]
