# Generated by Django 4.2.13 on 2024-06-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_conditionoforder_alter_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionoforder',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название состояния записи'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed', to='base.conditionoforder', verbose_name='Запись подтверждена'),
        ),
    ]
