# Generated by Django 4.2.13 on 2024-06-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_conditionoforder_name_alter_order_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed', to='base.conditionoforder', verbose_name='Запись подтверждена'),
        ),
    ]
