# Generated by Django 4.2.13 on 2024-06-18 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
